### ISSUE TITLE
missing tutorial link

### ISSUE THREAD

**Issue by nasum** [yhara/ovto#4]
There seems to be no tutorial link.

https://github.com/yhara/ovto/blob/d53fa9df6ed321b279690c9d82fd51908b7ed1db/README.md#L62

![image](https://user-images.githubusercontent.com/1456806/56404967-b60d6300-62a4-11e9-97d3-3feb050fb45b.png)

**Comment by yhara** [comment]
Fixed by a5377cb. Thanks!
