### ISSUE TITLE
Why Foo.run called two times with different ids?

### ISSUE THREAD

**Issue by sarbazx** [yhara/ovto#6]
Hi, seems to be simpel framework but in Rails installation there is `Foo.run(id: 'foo-app')` and `Foo.run(id: 'ovto-app')` in template, why it is called two times? also they are called with different ids? Why? is it necessary to call this function 2 times?

<img width="592" alt="image" src="https://user-images.githubusercontent.com/5629946/56456489-df49f400-6375-11e9-821a-a2d6ce0fc147.png">

**Comment by yhara** [comment]
> is it necessary to call this function 2 times?

No, you just need either one! I've fixed the doc. Thank you for your question.
